version: '3.0'

services:

  php:
    build:
      context: .
      dockerfile: php-dockerfile
    container_name: laracamp-php
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html
      - ./docker-files/php/usr/local/etc/php/conf.d/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - laravel
  
  nginx:
    image: nginx:stable-alpine
    container_name: laracamp-nginx
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "8098:80"
    volumes:
      - ./:/var/www/html
      - ./docker-files/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel
  
  mysql:
    image: mysql:5.7.22
    container_name: laracamp-mysql
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "5306:3306"
    environment:
      MYSQL_DATABASE: laracamp
      MYSQL_ROOT_PASSWORD: 12345
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-files/mysql/etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laracamp-phpmyadmin
    restart: always
    ports:
      - "8099:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
    driver: local